/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ikki_3d (https://sketchfab.com/jthulhu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rubber-duck-f1de4fc390db4266a509b9739350512a
title: Rubber duck
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('../public/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 173.29, -2.92]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.9, 1.09, 1.02]}>
            <mesh
              geometry={nodes.defaultMaterial.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('../public/scene.gltf');
